function patchSimulatorSourceV16(source){
  source=source.replace(/Thornton WTP Operator Simulator V1[34][^<\n]*/g,'Thornton WTP Operator Simulator V16 — Interactive HMI')
    .replace('THORNTON WTP // OPERATOR SIM V14','THORNTON WTP // OPERATOR SIM V16')
    .replace('THORNTON WTP // OPERATOR SIM V13','THORNTON WTP // OPERATOR SIM V16')
    .replace('function step(){','function step(){\n    if(state.homePaused)return;');
  const css=`
  .v16-home{position:fixed;inset:0;z-index:3000;background:rgba(7,10,13,.9);backdrop-filter:blur(8px);display:flex;align-items:center;justify-content:center;padding:24px}.v16-home.hidden{display:none}.v16-panel{width:min(1180px,96vw);max-height:92vh;overflow:auto;display:grid;grid-template-columns:1.25fr .95fr;background:#161c22;border:1px solid #34404a;border-radius:18px;box-shadow:0 20px 60px #0008}.v16-photo{min-height:360px;background:#0e1317}.v16-photo img{width:100%;height:100%;object-fit:cover;display:block;min-height:360px}.v16-copy{padding:28px;display:flex;flex-direction:column;justify-content:center}.v16-copy>small{color:#7eb7df;letter-spacing:.15em;font-weight:700}.v16-copy h1{font-size:34px;margin:10px 0}.v16-copy p{color:#b4c0c8;line-height:1.55}.v16-meta,.v16-actions{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:12px 0}.v16-meta div{background:#11171c;border:1px solid #313c47;border-radius:10px;padding:10px}.v16-meta span{display:block;color:#91a0aa;font-size:10px}.v16-meta b{display:block;margin-top:4px}.v16-actions .btn{padding:11px}.v16-scen{display:none;background:#11171c;border:1px solid #313c47;border-radius:10px;padding:10px}.v16-scen.show{display:grid;grid-template-columns:repeat(2,1fr);gap:7px}.v16-scen .btn{text-align:left}.v16-scen span{display:block;color:#93a3ad;font-size:9px;margin-top:2px;font-weight:400}
  .v16-card .schematic-wrap{padding:10px 14px 12px}.v16-svg{display:block;width:100%;height:auto;background:#11171c;border:1px solid #313c47;border-radius:12px}.v16-svg .pipe{stroke:#2fd5c4;stroke-width:7;fill:none;stroke-linecap:round}.v16-svg .tank{fill:#202a32;stroke:#50616e;stroke-width:2}.v16-svg .gac{fill:#303826}.v16-svg .filter{fill:#223426}.v16-svg .store{fill:#29313a}.v16-svg text{font-family:Segoe UI,Arial,sans-serif;text-anchor:middle;dominant-baseline:middle;fill:#e8eef2}.v16-svg .small{font-size:10px;fill:#9caab4}.v16-svg .lab{font-size:13px;font-weight:700}.v16-v{cursor:pointer}.v16-v circle{fill:#252c32;stroke:#7f8d97;stroke-width:2.5;transition:.35s}.v16-v path{stroke:#e4ebef;stroke-width:2.4;transform-box:fill-box;transform-origin:center;transition:.5s}.v16-v.open circle{fill:#173929;stroke:#42d07d}.v16-v.open path{transform:rotate(90deg)}.v16-v.moving circle{fill:#4a3b16;stroke:#ffc857;animation:v16pulse .6s infinite alternate}.v16-v.moving path{animation:v16move .6s infinite alternate}.v16-v.fault circle{fill:#4b2026;stroke:#ff6b6b;animation:v16fault .5s infinite alternate}.v16-v text{font-size:9px;fill:#aebbc3}.v16-p circle{fill:#252c32;stroke:#71818d;stroke-width:2.5}.v16-p.run circle{fill:#173929;stroke:#42d07d;animation:v16pulse 1s infinite alternate}.v16-p.trip circle{fill:#4b2026;stroke:#ff6b6b;animation:v16fault .5s infinite alternate}.v16-fill{fill:#2d92c4;opacity:.55;transition:y .7s,height .7s}.v16-legend{display:flex;gap:12px;flex-wrap:wrap;padding:0 14px 12px;color:#93a3ad;font-size:9px}.v16-legend i{display:inline-block;width:8px;height:8px;border-radius:50%;margin-right:4px}.v16-legend .o{background:#42d07d}.v16-legend .c{background:#7f8d97}.v16-legend .m{background:#ffc857}.v16-legend .f{background:#ff6b6b}@keyframes v16pulse{to{filter:brightness(1.35)}}@keyframes v16fault{to{filter:brightness(1.5)}}@keyframes v16move{to{transform:rotate(90deg)}}@media(max-width:850px){.v16-panel{grid-template-columns:1fr}.v16-meta,.v16-actions,.v16-scen{grid-template-columns:1fr}.v16-photo img{min-height:220px}}
  `;
  source=source.replace('</style>',css+'\n</style>');
  const home=`<div class="v16-home" id="v16Home"><div class="v16-panel"><div class="v16-photo"><img id="v16Photo" alt="Thornton Water Treatment Plant site view"></div><div class="v16-copy"><small>THORNTON WATER TREATMENT PLANT</small><h1>Operator Shift Simulator</h1><p>Enter a randomized shift, resume a saved shift, or choose a targeted training scenario. The image is scene-setting; the controls and schematics remain generalized training fiction.</p><div class="v16-meta"><div><span>SHIFT</span><b>12 HOURS</b></div><div><span>MODE</span><b>SCADA / OPERATOR</b></div><div><span>BUILD</span><b>V16</b></div></div><div class="v16-actions"><button class="btn good" id="v16Start">Start New Shift</button><button class="btn" id="v16Resume">Resume Shift</button><button class="btn" id="v16Scenario">Scenario</button></div><div class="v16-scen" id="v16Scen"><button class="btn" data-v16s="source">Source-water challenge<span>Turbidity, alkalinity, coagulation</span></button><button class="btn" data-v16s="chemical">Chemical / analyzer challenge<span>Feed deviations and verification</span></button><button class="btn" data-v16s="filter">Filter / backwash challenge<span>Loading, basin, actuator faults</span></button><button class="btn" data-v16s="distribution">Distribution challenge<span>Demand, tanks, pumps, PRVs</span></button><button class="btn" data-v16s="pfas">PFAS GAC challenge<span>Media, headloss, lab trends</span></button><button class="btn" data-v16s="random">Randomized shift<span>Mixed incident pool</span></button></div></div></div></div>`;
  source=source.replace('<body>','<body>'+home);
  const runtime=`
  state.homePaused=true;state.hmiManualValves=state.hmiManualValves||{};state.hmiValveTransitions=state.hmiValveTransitions||{};const V16SAVE='thorntonWtpV16Save';
  const v16V=(k,x,y,op=1)=>\`<g class="v16-v open" data-v16v="\${k}" data-op="\${op}" transform="translate(\${x} \${y})"><circle r="17"/><path d="M-11 -11 L11 11 M11 -11 L-11 11"/><text y="29">OPEN</text></g>\`;
  const v16P=(k,x,y)=>\`<g class="v16-p" data-v16p="\${k}" transform="translate(\${x} \${y})"><circle r="21"/><text class="lab">P</text></g>\`;
  const v16Card=(title,note,svg)=>\`<div class="card scada-card v16-card"><div class="section-title">\${title}</div><div class="page-inline-note">\${note}</div><div class="schematic-wrap">\${svg}</div><div class="v16-legend"><span><i class="o"></i>OPEN/RUN</span><span><i class="c"></i>CLOSED/OFF</span><span><i class="m"></i>MOVING</span><span><i class="f"></i>FAULT/TRIP</span><span>Click valves for status / generalized training commands.</span></div></div>\`;
  function v16Svg(type){let s='';if(type==='treatment')s=\`<svg class="v16-svg" viewBox="0 0 980 220"><line class="pipe" x1="60" y1="110" x2="920" y2="110"/><rect class="tank" x="30" y="65" width="100" height="90" rx="10"/><text class="lab" x="80" y="105">RAW</text>\${v16V('t_raw',160,110)}<rect class="tank" x="205" y="55" width="125" height="110" rx="10"/><text class="lab" x="267" y="100">COAG/FLOC</text>\${v16V('t_settle',365,110)}<rect class="tank" x="405" y="55" width="125" height="110" rx="10"/><text class="lab" x="467" y="100">SETTLING</text>\${v16V('t_ozone',565,110)}<rect class="tank" x="605" y="65" width="90" height="90" rx="40"/><text class="lab" x="650" y="105">OZONE</text>\${v16V('t_filter',730,110)}<rect class="tank filter" x="770" y="55" width="110" height="110" rx="10"/><text class="lab" x="825" y="100">FILTERS</text>\${v16V('t_finish',910,110)}</svg>\`;
  if(type==='filters')s=\`<svg class="v16-svg" viewBox="0 0 980 230"><line class="pipe" x1="60" y1="55" x2="920" y2="55"/><line class="pipe" x1="60" y1="185" x2="920" y2="185"/><rect class="tank filter" x="100" y="85" width="470" height="75" rx="10"/><text class="lab" x="335" y="115">6-FILTER GALLERY</text>\${v16V('bw_influent',620,55,0)}\${v16V('bw_effluent',680,185,0)}\${v16V('bw_waste',745,185,0)}\${v16V('bw_air',810,120,0)}\${v16V('bw_water',875,120,0)}<rect class="tank" x="810" y="160" width="120" height="50" rx="8"/><text class="small" x="870" y="185">BW BASIN</text></svg>\`;
  if(type==='pfas')s=\`<svg class="v16-svg" viewBox="0 0 980 220"><line class="pipe" x1="60" y1="110" x2="920" y2="110"/><rect class="tank filter" x="25" y="70" width="110" height="80" rx="10"/><text class="small" x="80" y="110">FILTERED</text>\${v16V('pfas_in',180,110)}<rect class="tank gac" x="230" y="45" width="120" height="130" rx="45"/><text class="lab" x="290" y="110">GAC A</text>\${v16V('pfas_mid1',390,110,0)}<rect class="tank gac" x="440" y="45" width="120" height="130" rx="45"/><text class="lab" x="500" y="110">GAC B</text>\${v16V('pfas_mid2',600,110,0)}<rect class="tank gac" x="650" y="45" width="120" height="130" rx="45"/><text class="lab" x="710" y="110">GAC C</text>\${v16V('pfas_out',815,110)}<rect class="tank" x="860" y="70" width="90" height="80" rx="10"/><text class="small" x="905" y="110">TO CL</text></svg>\`;
  if(type==='chemicals')s=\`<svg class="v16-svg" viewBox="0 0 980 230"><line class="pipe" x1="70" y1="180" x2="920" y2="180"/><rect class="tank" x="85" y="35" width="100" height="80" rx="10"/><text class="small" x="135" y="70">FERRIC</text>\${v16P('chem_ferric',135,145)}<rect class="tank" x="235" y="35" width="100" height="80" rx="10"/><text class="small" x="285" y="70">OZONE</text>\${v16P('chem_ozone',285,145)}<rect class="tank" x="385" y="35" width="100" height="80" rx="10"/><text class="small" x="435" y="70">CHLORINE</text>\${v16P('chem_chlorine',435,145)}<rect class="tank" x="535" y="35" width="100" height="80" rx="10"/><text class="small" x="585" y="70">AMMONIA</text>\${v16P('chem_ammonia',585,145)}<rect class="tank" x="685" y="35" width="100" height="80" rx="10"/><text class="small" x="735" y="70">CAUSTIC</text>\${v16P('chem_caustic',735,145)}\${v16V('chem_header',850,180,0)}</svg>\`;
  if(type==='distribution')s=\`<svg class="v16-svg" viewBox="0 0 980 220"><line class="pipe" x1="60" y1="110" x2="920" y2="110"/><rect class="tank" x="25" y="65" width="110" height="90" rx="10"/><text class="lab" x="80" y="105">TWTP</text>\${v16P('dist_pump',190,110)}\${v16V('dist_main',270,110)}<rect class="tank store" x="350" y="25" width="90" height="75" rx="10"/><rect class="v16-fill" data-v16fill="0" x="354" y="65" width="82" height="31"/><rect class="tank store" x="500" y="130" width="90" height="75" rx="10"/><rect class="v16-fill" data-v16fill="1" x="504" y="170" width="82" height="31"/>\${v16V('dist_prv',670,110)}<rect class="tank" x="730" y="65" width="190" height="90" rx="10"/><text class="lab" x="825" y="100">PRESSURE ZONES</text></svg>\`;
  if(type==='tanks'){let x='';for(let i=0;i<9;i++){const px=20+i*105;x+=\`<g><rect class="tank" x="\${px}" y="40" width="78" height="130" rx="12"/><rect class="v16-fill" data-v16fill="\${i}" x="\${px+4}" y="100" width="70" height="66"/><text class="lab" x="\${px+39}" y="65">T\${i+1}</text><text class="small" data-v16tl="\${i}" x="\${px+39}" y="190">--%</text></g>\`;}s=\`<svg class="v16-svg" viewBox="0 0 980 220">\${x}</svg>\`;}
  if(type==='pumps'){let x='<line class="pipe" x1="60" y1="110" x2="920" y2="110"/>';for(let i=0;i<7;i++){const px=105+i*125;x+=v16P(String(i+1),px,110);if(i<6)x+=v16V('ps_'+(i+1),px+62,110,0)}s=\`<svg class="v16-svg" viewBox="0 0 980 220">\${x}</svg>\`;}return s;}
  function v16AddCards(){const cfg={treatment:['INTERACTIVE PROCESS SCHEMATIC','Generalized tanks and animated valve states.'],filters:['FILTER / BACKWASH SCHEMATIC','Backwash valves follow automatic command/feedback and fault states.'],pfas:['PFAS GAC SCHEMATIC','Future-state GAC valves animate with system state.'],chemicals:['CHEMICAL FEED SCHEMATIC','Feed pumps respond to dose/feed events.'],distribution:['DISTRIBUTION SCHEMATIC','Storage fills and PRV/pump status update live.'],tanks:['LIVE STORAGE SCHEMATIC','Nine modeled tank levels update continuously.'],pumps:['PUMP STATION SCHEMATIC','Seven modeled station pump states update live.']};Object.entries(cfg).forEach(([id,a])=>{const sec=document.querySelector('.scada-page[data-page-id="'+id+'"]');if(sec&&!sec.querySelector('.v16-card'))sec.insertAdjacentHTML('afterbegin',v16Card(a[0],a[1],v16Svg(id)))})}
  function v16ValveState(k){const t=state.hmiValveTransitions[k];if(t&&Date.now()<t.until)return'MOVING';if(t){state.hmiManualValves[k]=t.target;delete state.hmiValveTransitions[k]}if(state.hmiManualValves[k])return state.hmiManualValves[k];if(k.startsWith('bw_')){const a=bwActuatorStates(),m={bw_influent:0,bw_effluent:1,bw_waste:2,bw_air:3,bw_water:4},q=a[m[k]];return!q?'CLOSED':q.status==='fault'?'FAULT':q.status==='moving'?'MOVING':q.feedback==='OPEN'?'OPEN':'CLOSED'}if(k.startsWith('pfas_'))return state.pfas.mode==='ONLINE'?'OPEN':'CLOSED';if(k==='dist_prv')return state.prv.abnormal?'FAULT':'OPEN';if(k.startsWith('ps_')){const p=state.pumps[(+k.split('_')[1])-1];return p?.trip?'FAULT':p?.run?'OPEN':'CLOSED'}return +controls.flow.value>0?'OPEN':'CLOSED'}
  function v16PumpState(k){if(k==='chem_ferric')return state.event==='coagfeed'?'TRIP':+controls.coag.value>0?'RUN':'OFF';if(k==='chem_ozone')return state.event==='ozfault'?'TRIP':+controls.ozone.value>0?'RUN':'OFF';if(k==='chem_chlorine')return state.event==='clfeed'?'TRIP':+controls.chlorine.value>0?'RUN':'OFF';if(k==='chem_ammonia')return +controls.ammonia.value>0?'RUN':'OFF';if(k==='chem_caustic')return state.event==='causticfeed'?'TRIP':+controls.caustic.value>0?'RUN':'OFF';if(k==='dist_pump')return state.pumps.some(p=>p.run)?'RUN':'OFF';const p=state.pumps[(+k)-1];return p?.trip?'TRIP':p?.run?'RUN':'OFF'}
  function v16Render(){document.querySelectorAll('[data-v16v]').forEach(g=>{const s=v16ValveState(g.dataset.v16v);g.classList.remove('open','closed','moving','fault');g.classList.add(s.toLowerCase());const t=g.querySelector('text');if(t)t.textContent=s});document.querySelectorAll('[data-v16p]').forEach(g=>{const s=v16PumpState(g.dataset.v16p);g.classList.remove('run','trip');if(s!=='OFF')g.classList.add(s.toLowerCase())});document.querySelectorAll('[data-v16fill]').forEach(r=>{const i=+r.dataset.v16fill,t=state.tanks[i];if(!t)return;const max=type=>0;const y0=(r.closest('svg').getAttribute('viewBox').includes('220')?40:40);const h0=(r.closest('.scada-page')?.dataset.pageId==='tanks'?130:75),base=(r.closest('.scada-page')?.dataset.pageId==='tanks'?170:(i===0?100:205)),ih=(h0-8)*Math.max(0,Math.min(100,t.level))/100;r.setAttribute('y',base-4-ih);r.setAttribute('height',ih);const l=document.querySelector('[data-v16tl="'+i+'"]');if(l)l.textContent=Math.round(t.level)+'%'})}
  function v16Bind(){document.querySelectorAll('[data-v16v]').forEach(g=>{g.onclick=()=>{const k=g.dataset.v16v,s=v16ValveState(k),op=g.dataset.op==='1';if(!op){showModal('Valve Status',\`<p><b>\${k.toUpperCase()}</b>: <b>\${s}</b></p><p>This valve follows the simulator's automatic state.</p>\`);return}const target=s==='OPEN'?'CLOSED':'OPEN';showModal('Generalized Valve Command',\`<p><b>\${k.toUpperCase()}</b> is \${s}. Command \${target}?</p><p>This is a schematic training command, not a real Thornton valve tag or SOP.</p><div class="row"><button class="btn good" id="v16vc">Command \${target}</button></div>\`);setTimeout(()=>{const b=$('v16vc');if(b)b.onclick=()=>{state.hmiValveTransitions[k]={target,until:Date.now()+1300};log('Generalized schematic valve '+k+' commanded '+target+'.');$('modal').classList.remove('show')}},0)}})}
  function v16Save(){if(state.homePaused||state.ended)return;try{const p={state:JSON.parse(JSON.stringify(state)),controls:{},alarms:[...activeAlarms.entries()],tasks:ROUTINE_TASKS.map(t=>({id:t.id,completed:t.completed,completedAt:t.completedAt,overdueHits:t.overdueHits,finding:t.finding}))};Object.keys(controls).forEach(k=>p.controls[k]=controls[k].value);localStorage.setItem(V16SAVE,JSON.stringify(p));const b=$('v16Resume');if(b)b.disabled=false}catch(e){}}
  function v16Resume(){try{const p=JSON.parse(localStorage.getItem(V16SAVE));Object.assign(state,p.state);Object.entries(p.controls||{}).forEach(([k,v])=>{if(controls[k])controls[k].value=v});activeAlarms.clear();(p.alarms||[]).forEach(([k,v])=>activeAlarms.set(k,v));(p.tasks||[]).forEach(s=>{const t=ROUTINE_TASKS.find(x=>x.id===s.id);if(t)Object.assign(t,s)});state.homePaused=false;$('v16Home').classList.add('hidden');render();return true}catch(e){return false}}
  function v16New(){try{localStorage.removeItem(V16SAVE)}catch(e){}state.homePaused=false;$('v16Home').classList.add('hidden');log('New randomized shift started from Home screen.')}
  function v16Scenario(id){activeAlarms.clear();state.event=null;state.eventMeta=null;state.unresolved=0;state.minute=0;state.quality=state.efficiency=state.response=state.distribution=state.routineScore=100;ROUTINE_TASKS.forEach(t=>{t.completed=false;t.completedAt=null;t.overdueHits=0;t.finding=null});initializeRandomShift();const m={source:['storm','odor','alkshift','sludge','coagfeed','sourcepump','analyzer','filterbreak'],chemical:['clfeed','coagfeed','causticfeed','analyzer','inventory','ozfault','power','scadacomm'],filter:['filterbreak','storm','sludge','power','analyzer','coagfeed','ozfault','sourcepump'],distribution:['demand','fireflow','mainbreak','pumptrip','prvfault','scadacomm','power','sourcepump'],pfas:['pfashl','pfasbreak','pfasload','analyzer','sourcepump','power','scadacomm','demand']};if(id!=='random'){state.shiftIssueIds=m[id];state.shiftIssueRemaining=[...m[id]];state.shiftProfile={name:id.toUpperCase()+' CHALLENGE',description:'Targeted V16 scenario'};if(id==='source'){state.rawTurb=7;state.rawAlk=48}if(id==='chemical'){state.finishCl=1.4;state.rawAlk=50}if(id==='filter'){let f=[...state.filters].sort((a,b)=>b.run-a.run)[0];f.run=270;f.head=7.8;f.turb=.094;state.bwBasin=.68}if(id==='distribution'){state.cityDemand=38;[...state.tanks].sort((a,b)=>a.level-b.level)[0].level=40}if(id==='pfas'){state.pfas.mediaRemaining=.27;state.pfas.headloss=4.1;state.pfas.sampleAgeDays=14}}state.homePaused=false;$('v16Home').classList.add('hidden');log('Scenario started: '+(state.shiftProfile?.name||'Randomized Shift'));render()}
  const v16OldRender=render;render=function(){v16OldRender();v16Render()};
  window.addEventListener('beforeunload',v16Save);setInterval(v16Save,5000);setInterval(v16Render,500);window.addEventListener('load',()=>{fetch('app/site-image.txt?v=16').then(r=>r.text()).then(x=>$('v16Photo').src='data:image/jpeg;base64,'+x.trim()).catch(()=>{});v16AddCards();v16Bind();v16Render();const r=$('v16Resume');r.disabled=!localStorage.getItem(V16SAVE);$('v16Start').onclick=v16New;r.onclick=()=>v16Resume();$('v16Scenario').onclick=()=>$('v16Scen').classList.toggle('show');document.querySelectorAll('[data-v16s]').forEach(b=>b.onclick=()=>v16Scenario(b.dataset.v16s))});
  `;
  const i=source.lastIndexOf('</script>');if(i>0)source=source.slice(0,i)+runtime+source.slice(i);return source;
}
